name: truee_balance_app
description: "A Truee Balance."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Image
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # Slider
  carousel_slider: ^5.0.0

  # Dio
  dio: ^5.7.0

  # Language
  easy_localization: ^3.0.7

  # State Management
  flutter_bloc: ^9.0.0

  # Loading
  flutter_easyloading: ^3.0.5
  loading_indicator: ^3.1.1

  # Phoenix
  flutter_phoenix: ^1.1.1

  # Responsive
  flutter_screenutil: ^5.9.3

  # Secure Data
  flutter_secure_storage: ^9.2.4

  # SVG
  flutter_svg: ^2.0.17

  # Show Toast Bar
  fluttertoast: ^8.2.10

  # Freezed
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4

  # Dependency Injection
  get_it: ^8.0.3

  # Json
  json_annotation: ^4.9.0

  # Lottie
  lottie: ^3.3.1

  # Animation
  page_transition: ^2.2.1
  smooth_page_indicator: ^1.2.0+3

  # OTP
  pinput: ^5.0.1

  # Shared Preferences
  shared_preferences: ^2.3.5

  # Skeleton
  skeletonizer: ^1.4.3

  # Table Calendar
  table_calendar: null

  # Icons
  iconsax: ^0.0.8


  # Common
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  video_player: ^2.9.5


dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.9.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/videos/
    - assets/lotties/
    - assets/languages/
    - assets/images/svg/
    - assets/images/png/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/themes/
  filename: assets.dart