name: truee_balance_app
description: "A Truee Balance."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.0
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  easy_localization: ^3.0.7
  file_picker: ^10.3.2
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^19.3.0
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  lottie: ^3.3.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.5
  skeletonizer: ^1.4.3
  smooth_page_indicator: ^1.2.0+3
  table_calendar: null
  url_launcher: ^6.3.1
  video_player: ^2.9.5
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/lotties/
    - assets/languages/
    - assets/images/svg/
    - assets/images/png/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/themes/
  filename: assets.dart
